#!/usr/bin/env python
# Copyright (c) 2008 Chris Moyer http://coredumped.org
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish, dis-
# tribute, sublicense, and/or sell copies of the Software, and to permit
# persons to whom the Software is furnished to do so, subject to the fol-
# lowing conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
# OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABIL-
# ITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT
# SHALL THE AUTHOR BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, 
# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

def get_function(session, f_name):
	"""
	Get function f_name (starting point of session)
	"""
	cmd_list = f_name.split(".")
	func = session[cmd_list.pop(0)]
	for cmd in cmd_list:
		func = getattr(func, cmd)
	return func

if __name__ == "__main__":
	import sys
	sys.path.append(".")
	from optparse import OptionParser
	from paste import httpserver
	import boto_web
	from boto_web.environment import Environment

	parser = OptionParser(usage="usage: %prog [options] application")
	parser.add_option("-e", "--environment", dest="env", default=None, help="Environment file to use")
	parser.add_option("-p", "--port", dest="port", default="8080", help="Port to run on (default 8080)")
	parser.add_option("--host", dest="hostname", default="localhost", help="Hostname to run on (default localhost)")
	parser.add_option("-v", action="count", dest="verbose", default=0)
	(options, args) = parser.parse_args()

	e = Environment(args[0], options.env)
	import boto
	boto.config = e.config

	from paste import httpserver
	from boto_web.appserver.url_mapper import URLMapper
	from boto_web.appserver.filter_mapper import FilterMapper
	mapper = FilterMapper(app=URLMapper(e), env=e)
	
	httpserver.serve(mapper, host=options.hostname, port=int(options.port))
