#!/usr/bin/env python
# Copyright (c) 2009 Chris Moyer http://coredumped.org
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish, dis-
# tribute, sublicense, and/or sell copies of the Software, and to permit
# persons to whom the Software is furnished to do so, subject to the fol-
# lowing conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
# OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABIL-
# ITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT
# SHALL THE AUTHOR BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, 
# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

if __name__ == "__main__":
	import sys
	sys.path.append(".")
	from optparse import OptionParser
	from botoweb.client.environment import Environment
	import code
	import readline

	parser = OptionParser()
	parser.add_option("-p", "--port", dest="port", default="8080", help="Port to connect to (default 8080)")
	parser.add_option("--host", dest="hostname", default="localhost", help="Host to connect to (default localhost)")
	parser.add_option("-s", "--ssl", default=False, action="store_true", help="Use SSL")
	parser.add_option("-v", action="count", dest="verbose", default=0)
	(options, args) = parser.parse_args()

	env = Environment(options.hostname, int(options.port), options.ssl)
	code.interact(local={ "env": env})
