#!/usr/bin/env python
# Copyright (c) 2008 Chris Moyer http://coredumped.org
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish, dis-
# tribute, sublicense, and/or sell copies of the Software, and to permit
# persons to whom the Software is furnished to do so, subject to the fol-
# lowing conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
# OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABIL-
# ITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT
# SHALL THE AUTHOR BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, 
# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

def get_function(session, f_name):
	"""
	Get function f_name (starting point of session)
	"""
	cmd_list = f_name.split(".")
	func = session[cmd_list.pop(0)]
	for cmd in cmd_list:
		func = getattr(func, cmd)
	return func

if __name__ == "__main__":
	import readline
	from paste import httpserver
	import boto_web
	import boto_web.appserver
	import boto_web.filterserver
	import sys
	sys.path.append(".")
	sys.ps1 = "\x01\x1b[34m\x1b[1m\x02>>> \x01\x1b[0m\x02"
	sys.ps2 = "... "
	import code
	session = {}
	session['appserver'] = boto_web.appserver
	session['filterserver'] = boto_web.filterserver
	from boto_web.resources.user import User
	session['User'] = User
	from boto_web.resources.filter_rule import FilterRule
	session['FilterRule'] = FilterRule
	session['help'] = "boto_web Version %s" % boto_web.Version

	if len(sys.argv) > 1:
		cmd = get_function(session, sys.argv[1])
		args = []
		if len(sys.argv) > 2:
			args = sys.argv[2:]
		cmd(*args)
	else:
		code.interact(banner=session['help'], local=session)
